/**
 * Offline trainer: builds per-language dictionaries, top-64 literal charsets, and static
 * entropy tables by running the real codec pipeline over the train split of the corpus
 * (`.corpus/<lang>/`), then emits generated modules under src/generated/.
 *
 * Usage:
 *   bun scripts/train/train.ts core            # wrapper dictionary + id-0 generic tables
 *   bun scripts/train/train.ts typescript ...  # one or more language modules
 *   bun scripts/train/train.ts --all           # core + every language with corpus data
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { EntropyTables, RegisteredLanguage } from '../../src/dictionary.ts';
import {
  MIN_LEN_REP,
  TOKEN_ALPHABET_SIZE,
  TOKEN_KIND_DICT,
  TOKEN_KIND_HISTORY,
  TOKEN_KIND_LITRUN,
  TOKEN_KIND_REP0,
} from '../../src/format.ts';
import { buildLengths } from '../../src/huffman.ts';
import { LANGUAGE_IDS } from '../../src/languageIds.ts';
import { dictIndexFor, parse } from '../../src/lz.ts';
import { toBase64 } from '../../src/moduleData.ts';
import { smallPricing } from '../../src/smallMode.ts';
import { LENGTH_SLOT_COUNT, OFFSET_SLOT_COUNT, slotOf } from '../../src/slots.ts';
import { trainDictionary } from './trainDictionary.ts';
import { buildWrapperDictionary } from './wrapperContent.ts';

const ROOT = join(import.meta.dir, '../..');
const CORPUS_DIR = join(ROOT, '.corpus');
const GENERATED_DIR = join(ROOT, 'src/generated');
const LANGUAGES_DIR = join(ROOT, 'src/languages');
const DICTIONARY_BUDGET_BYTES = 20 * 1024;
/** Bound on per-language statistics input; keeps a full training run tractable. */
const MAX_STATS_BYTES = 8 * 1024 * 1024;

const textEncoder = new TextEncoder();

function main(): void {
  const args = process.argv.slice(2);
  const targets = args.includes('--all')
    ? ['core', ...Object.keys(LANGUAGE_IDS).filter((name) => name !== 'none' && hasCorpus(name))]
    : args;
  if (targets.length === 0) {
    console.error('usage: bun scripts/train/train.ts [--all] [core] [<language> ...]');
    process.exit(1);
  }
  mkdirSync(GENERATED_DIR, { recursive: true });
  mkdirSync(LANGUAGES_DIR, { recursive: true });
  for (const target of targets) {
    if (target === 'core') trainCore();
    else trainLanguageModule(target);
  }
  updateBarrel();
}

/** Regenerates src/languages/index.ts to import every trained module (self-registration). */
function updateBarrel(): void {
  const modules = readdirSync(LANGUAGES_DIR)
    .filter((name) => name.endsWith('.ts') && name !== 'index.ts')
    .toSorted();
  const imports = modules.map((name) => `import './${name}';`).join('\n');
  const body = modules.length > 0 ? `${imports}\n` : 'export {};\n';
  writeFileSync(
    join(LANGUAGES_DIR, 'index.ts'),
    `// Generated by scripts/train/train.ts — do not edit by hand.
// Barrel importing every trained language module (each self-registers on import).
${body}`
  );
}

function trainCore(): void {
  const wrapper = buildWrapperDictionary();
  // Generic id-0 tables train on the plain-text corpus when available, else on a built-in sample.
  const docs = hasCorpus('text') ? loadTrainDocs('text') : [FALLBACK_SAMPLE];
  const { top64, tables } = trainStatistics(docs, wrapper, new Uint8Array(0));
  const source = `${GENERATED_HEADER}import type { LanguageModuleData } from '../dictionary.ts';
import { fromBase64 } from '../moduleData.ts';

/** Shared wrapper dictionary (markdown/JSON scaffolding + generic prose), offset 0 in every language. */
export const wrapperDictionary: Uint8Array = fromBase64('${toBase64(wrapper)}');

/** The dictionary-less \`none\` path: id 0, wrapper dictionary only, generic tables. */
export const id0Module: LanguageModuleData = {
  id: 0,
  name: 'none',
  dictionarySuffix: new Uint8Array(0),
${moduleDataFields(top64, tables)}};
`;
  writeFileSync(join(GENERATED_DIR, 'core.ts'), source);
  console.log(`core: wrapper ${wrapper.length} B, tables trained on ${docs.length} doc(s)`);
}

function trainLanguageModule(name: string): void {
  const id = LANGUAGE_IDS[name];
  if (id === undefined || id === 0) throw new Error(`unknown language: ${name}`);
  const docs = loadTrainDocs(name);
  if (docs.length === 0) throw new Error(`no train-split corpus for ${name} under ${CORPUS_DIR}/${name}`);
  const wrapper = buildWrapperDictionary();
  const wrapperText = new TextDecoder().decode(wrapper);
  const suffix = trainDictionary(docs, DICTIONARY_BUDGET_BYTES, wrapperText);
  const { top64, tables } = trainStatistics(docs, wrapper, suffix);

  const exportName = `${identifierFor(name)}Module`;
  const generated = `${GENERATED_HEADER}import type { LanguageModuleData } from '../dictionary.ts';
import { fromBase64 } from '../moduleData.ts';

export const ${exportName}: LanguageModuleData = {
  id: ${id},
  name: '${name}',
  dictionarySuffix: fromBase64('${toBase64(suffix)}'),
${moduleDataFields(top64, tables)}};
`;
  writeFileSync(join(GENERATED_DIR, `${identifierFor(name)}.ts`), generated);
  const registration = `import { ${exportName} } from '../generated/${identifierFor(name)}.ts';
import { registerLanguageModule } from '../moduleRegistry.ts';

// Self-registers on import; tables are validated at registration.
registerLanguageModule(${exportName});

export { ${exportName} };
`;
  writeFileSync(join(LANGUAGES_DIR, `${identifierFor(name)}.ts`), registration);
  console.log(`${name}: dictionary ${suffix.length} B, trained on ${docs.length} doc(s)`);
}

/**
 * Runs the real parser over the corpus with bootstrap tables, tallies per-stream symbol
 * frequencies, and rebuilds the tables from them; a second round re-parses with the trained
 * tables so prices and statistics converge.
 */
function trainStatistics(
  docs: string[],
  wrapper: Uint8Array,
  suffix: Uint8Array
): { top64: Uint8Array; tables: EntropyTables } {
  const dictionary = new Uint8Array(wrapper.length + suffix.length);
  dictionary.set(wrapper, 0);
  dictionary.set(suffix, wrapper.length);

  let top64 = rankTop64(byteFrequencies(docs));
  let tables = flatTables();
  let dictIndexHolder: RegisteredLanguage | undefined;
  for (let round = 0; round < 2; round++) {
    const language = makeLanguage(dictionary, top64, tables);
    if (dictIndexHolder) language.dictIndex = dictIndexHolder.dictIndex;
    dictIndexHolder = language;
    const literalFreqs = new Float64Array(256);
    const tokenFreqs = new Float64Array(TOKEN_ALPHABET_SIZE);
    const offsetFreqs = new Float64Array(OFFSET_SLOT_COUNT);
    let statsBytes = 0;
    for (const doc of docs) {
      if (statsBytes >= MAX_STATS_BYTES) break;
      const bytes = textEncoder.encode(doc);
      statsBytes += bytes.length;
      const tokens = parse(bytes, dictionary, dictIndexFor(language), smallPricing(bytes, language));
      for (const token of tokens) {
        if (token.type === 'lit') {
          const runValue = Math.min(token.end - token.start - 1, 262_143);
          tokenFreqs[TOKEN_KIND_LITRUN * LENGTH_SLOT_COUNT + slotOf(runValue)]!++;
          for (let i = token.start; i < token.end; i++) literalFreqs[bytes[i]!]!++;
        } else if (token.type === 'history') {
          const lenSlot = slotOf(token.len - MIN_LEN_REP);
          if (token.rep >= 0) tokenFreqs[(TOKEN_KIND_REP0 + token.rep) * LENGTH_SLOT_COUNT + lenSlot]!++;
          else {
            tokenFreqs[TOKEN_KIND_HISTORY * LENGTH_SLOT_COUNT + lenSlot]!++;
            offsetFreqs[slotOf(token.dist - 1)]!++;
          }
        } else {
          tokenFreqs[TOKEN_KIND_DICT * LENGTH_SLOT_COUNT + slotOf(token.len - MIN_LEN_REP)]!++;
          offsetFreqs[slotOf(token.start)]!++;
        }
      }
    }
    top64 = rankTop64(literalFreqs);
    tables = {
      literal: buildLengths(smoothed(literalFreqs)),
      token: buildLengths(smoothed(tokenFreqs)),
      offset: buildLengths(smoothed(offsetFreqs)),
    };
  }
  return { top64, tables };
}

function makeLanguage(dictionary: Uint8Array, top64: Uint8Array, tables: EntropyTables): RegisteredLanguage {
  const top64Index = new Int8Array(256).fill(-1);
  for (let i = 0; i < 64; i++) if (top64Index[top64[i]!] === -1) top64Index[top64[i]!] = i;
  return { id: -1, name: 'training', dictionary, top64, top64Index, tables, dictIndex: undefined };
}

function byteFrequencies(docs: string[]): Float64Array {
  const freqs = new Float64Array(256);
  for (const doc of docs) for (const byte of textEncoder.encode(doc)) freqs[byte]!++;
  return freqs;
}

function rankTop64(freqs: Float64Array): Uint8Array {
  const order = [...freqs.keys()].toSorted((a, b) => freqs[b]! - freqs[a]! || a - b);
  return new Uint8Array(order.slice(0, 64));
}

/** +1 smoothing: every symbol keeps a code, so encoders never lose the Huffman path. */
function smoothed(freqs: Float64Array): Float64Array {
  return freqs.map((f) => f + 1);
}

function flatTables(): EntropyTables {
  return {
    literal: buildLengths(new Float64Array(256).fill(1)),
    token: buildLengths(new Float64Array(TOKEN_ALPHABET_SIZE).fill(1)),
    offset: buildLengths(new Float64Array(OFFSET_SLOT_COUNT).fill(1)),
  };
}

function moduleDataFields(top64: Uint8Array, tables: EntropyTables): string {
  return `  top64: fromBase64('${toBase64(top64)}'),
  tables: {
    literal: fromBase64('${toBase64(tables.literal)}'),
    token: fromBase64('${toBase64(tables.token)}'),
    offset: fromBase64('${toBase64(tables.offset)}'),
  },
`;
}

function identifierFor(name: string): string {
  // 'en-US' → 'enUs' (strict camelCase, matching the repo's filename convention).
  return name.replaceAll(/-(\w+)/g, (_, part: string) => part[0]!.toUpperCase() + part.slice(1).toLowerCase());
}

function hasCorpus(name: string): boolean {
  return existsSync(join(CORPUS_DIR, name));
}

/** Train-split docs only; the manifest marks bench-split and copyleft-excluded samples. */
function loadTrainDocs(name: string): string[] {
  const dir = join(CORPUS_DIR, name);
  if (!existsSync(dir)) return [];
  const benchOnly = new Set<string>();
  const manifestPath = join(dir, 'manifest.jsonl');
  if (existsSync(manifestPath)) {
    for (const line of readFileSync(manifestPath, 'utf8').split('\n')) {
      if (!line.trim()) continue;
      const entry = JSON.parse(line) as { file: string; split?: string; trainable?: boolean };
      if (entry.split !== 'train' || entry.trainable === false) benchOnly.add(entry.file);
    }
  }
  const docs: string[] = [];
  const walk = (current: string, prefix: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const path = join(current, entry.name);
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(path, relative);
      else if (entry.name.endsWith('.txt') && !benchOnly.has(relative)) docs.push(readFileSync(path, 'utf8'));
    }
  };
  walk(dir, '');
  return docs;
}

const GENERATED_HEADER = `// Generated by scripts/train/train.ts — do not edit by hand.
// oxlint-disable -- generated file
`;

const FALLBACK_SAMPLE = `# tokzip generic sample
This built-in sample trains the id-0 tables when no plain-text corpus has been fetched.
It mixes short English prose with typical code and JSON payloads, because the id-0 path
must degrade gracefully on anything: chat messages, markdown documents, configuration
files, and source snippets. The quick brown fox jumps over the lazy dog. She sells sea
shells by the sea shore, and the shells she sells are surely seashells.

\`\`\`typescript
export function greet(name: string): string {
  return \`Hello, \${name}!\`;
}
for (let i = 0; i < 10; i++) console.log(greet(String(i)));
\`\`\`

{"name":"example","version":"1.0.0","dependencies":{"left-pad":"^1.3.0"},"private":true}

However, the training corpus should be fetched with scripts/corpus/fetchOss.ts for real
use; these few paragraphs only make the bootstrap tables sane rather than representative.
`;

main();
