/**
 * Offline trainer: builds per-language dictionaries, top-64 literal charsets, and static
 * entropy tables by running the real codec pipeline over the train split of the corpus
 * (from `TOKZIP_CORPUS_DIR` or the sibling tokzip-corpus checkout), then emits generated
 * modules under src/generated/.
 *
 * Usage:
 *   bun scripts/train/train.ts core            # wrapper dictionary + id-0 generic tables
 *   bun scripts/train/train.ts typescript ...  # one or more language modules
 *   bun scripts/train/train.ts --all           # core + every language with corpus data
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { EntropyTables, RegisteredLanguage } from '../../src/dictionary.ts';
import {
  LIT_CLASS_MAX,
  MIN_LEN_REP,
  OFFSET_CONTEXT_COUNT,
  OFFSET_CONTEXT_DICT,
  OFFSET_CONTEXT_HISTORY,
  TOKEN_ALPHABET_SIZE,
  TOKEN_CONTEXT_COUNT,
  TOKEN_KIND_DICT,
  TOKEN_KIND_HISTORY,
  TOKEN_KIND_LITRUN,
  TOKEN_KIND_REP0,
} from '../../src/format.ts';
import { buildLengths } from '../../src/huffman.ts';
import { LANGUAGE_IDS } from '../../src/languageIds.ts';
import { dictIndexFor, parse } from '../../src/lz.ts';
import { toBase64 } from '../../src/moduleData.ts';
import { smallPricing } from '../../src/smallMode.ts';
import { LENGTH_SLOT_COUNT, OFFSET_SLOT_COUNT, slotOf } from '../../src/slots.ts';
import { CORPUS_DIR } from '../corpus.ts';
import { trainDictionary } from './trainDictionary.ts';
import { buildWrapperDictionary } from './wrapperContent.ts';

const ROOT = join(import.meta.dir, '../..');
const GENERATED_DIR = join(ROOT, 'src/generated');
const LANGUAGES_DIR = join(ROOT, 'src/languages');
const DICTIONARY_BUDGET_BYTES = 512 * 1024;
/** Bound on per-language statistics input; keeps a full training run tractable. */
const MAX_STATS_BYTES = 32 * 1024 * 1024;

const textEncoder = new TextEncoder();

function main(): void {
  const args = process.argv.slice(2);
  const targets = args.includes('--all')
    ? ['core', ...Object.keys(LANGUAGE_IDS).filter((name) => name !== 'none' && hasCorpus(name))]
    : args;
  if (targets.length === 0) {
    console.error('usage: bun scripts/train/train.ts [--all] [core] [<language> ...]');
    process.exit(1);
  }
  mkdirSync(GENERATED_DIR, { recursive: true });
  mkdirSync(LANGUAGES_DIR, { recursive: true });
  for (const target of targets) {
    if (target === 'core') trainCore();
    else trainLanguageModule(target);
  }
  updateBarrel();
}

/** Regenerates src/languages/index.ts to import every trained module (self-registration). */
function updateBarrel(): void {
  const modules = readdirSync(LANGUAGES_DIR)
    .filter((name) => name.endsWith('.ts') && name !== 'index.ts')
    .toSorted();
  const imports = modules.map((name) => `import './${name}';`).join('\n');
  const body = modules.length > 0 ? `${imports}\n` : 'export {};\n';
  writeFileSync(
    join(LANGUAGES_DIR, 'index.ts'),
    `// Generated by scripts/train/train.ts — do not edit by hand.
// Barrel importing every trained language module (each self-registers on import).
${body}`
  );
}

function trainCore(): void {
  const wrapper = buildWrapperDictionary();
  // Generic id-0 tables train on the plain-text corpus when available, else on a built-in sample.
  const textDocs = loadTrainDocs('text');
  const docs = textDocs.length > 0 ? textDocs : [FALLBACK_SAMPLE];
  const { top64, tables } = trainStatistics(docs, wrapper, new Uint8Array(0));
  const source = `${GENERATED_HEADER}import type { LanguageModuleData } from '../dictionary.ts';
import { fromBase64 } from '../moduleData.ts';

/** Shared wrapper dictionary (markdown/JSON scaffolding + generic prose), offset 0 in every language. */
export const wrapperDictionary: Uint8Array = fromBase64('${toBase64(wrapper)}');

/** The dictionary-less \`none\` path: id 0, wrapper dictionary only, generic tables. */
export const id0Module: LanguageModuleData = {
  id: 0,
  name: 'none',
  dictionarySuffix: new Uint8Array(0),
${moduleDataFields(top64, tables)}};
`;
  writeFileSync(join(GENERATED_DIR, 'core.ts'), source);
  console.log(`core: wrapper ${wrapper.length} B, tables trained on ${docs.length} doc(s)`);
}

function trainLanguageModule(name: string): void {
  const id = LANGUAGE_IDS[name];
  if (id === undefined || id === 0) throw new Error(`unknown language: ${name}`);
  const docs = loadTrainDocs(name);
  if (docs.length === 0) throw new Error(`no train-split corpus for ${name} under ${CORPUS_DIR}/${name}`);
  const wrapper = buildWrapperDictionary();
  const wrapperText = new TextDecoder().decode(wrapper);
  const suffix = trainDictionary(docs, DICTIONARY_BUDGET_BYTES, wrapperText);
  const { top64, tables } = trainStatistics(docs, wrapper, suffix);

  const exportName = `${identifierFor(name)}Module`;
  const generated = `${GENERATED_HEADER}import type { LanguageModuleData } from '../dictionary.ts';
import { fromBase64 } from '../moduleData.ts';

export const ${exportName}: LanguageModuleData = {
  id: ${id},
  name: '${name}',
  dictionarySuffix: fromBase64('${toBase64(suffix)}'),
${moduleDataFields(top64, tables)}};
`;
  writeFileSync(join(GENERATED_DIR, `${identifierFor(name)}.ts`), generated);
  const registration = `import { ${exportName} } from '../generated/${identifierFor(name)}.ts';
import { registerLanguageModule } from '../moduleRegistry.ts';

// Self-registers on import; tables are validated at registration.
registerLanguageModule(${exportName});

export { ${exportName} };
`;
  writeFileSync(join(LANGUAGES_DIR, `${identifierFor(name)}.ts`), registration);
  console.log(`${name}: dictionary ${suffix.length} B, trained on ${docs.length} doc(s)`);
}

/** Joint symbol frequencies collected from one parse pass, split into two folds for validation. */
interface StreamStatistics {
  /** Literal frequencies by previous-byte context, per fold: `[fold][ctx * 256 + byte]`. */
  literal: [Float64Array, Float64Array];
  /** Token-symbol frequencies by previous-token-kind context: `[ctx * TOKEN_ALPHABET_SIZE + symbol]`. */
  token: Float64Array;
  /** Offset-slot frequencies by match-kind context: `[ctx * OFFSET_SLOT_COUNT + slot]`. */
  offset: Float64Array;
}

/**
 * Runs the real parser over the corpus with bootstrap tables, tallies per-stream symbol
 * frequencies per context, and rebuilds the tables from them; later rounds re-parse with the
 * trained tables so prices and statistics converge. Literal contexts (the previous byte) are
 * greedily merged into classes; the class count is chosen by two-fold cross-validation.
 */
function trainStatistics(
  docs: string[],
  wrapper: Uint8Array,
  suffix: Uint8Array
): { top64: Uint8Array; tables: EntropyTables } {
  const dictionary = new Uint8Array(wrapper.length + suffix.length);
  dictionary.set(wrapper, 0);
  dictionary.set(suffix, wrapper.length);

  let top64 = rankTop64(byteFrequencies(docs));
  let tables = flatTables();
  let dictIndexHolder: RegisteredLanguage | undefined;
  for (let round = 0; round < 3; round++) {
    const language = makeLanguage(dictionary, top64, tables);
    if (dictIndexHolder) language.dictIndex = dictIndexHolder.dictIndex;
    dictIndexHolder = language;
    const stats = collectStatistics(docs, dictionary, language);
    const literalFull = new Float64Array(256 * 256);
    for (let i = 0; i < literalFull.length; i++) literalFull[i] = stats.literal[0][i]! + stats.literal[1][i]!;
    top64 = rankTop64(marginalLiteralFreqs(literalFull));
    const { litContext, litClassCount } = chooseLiteralClasses(stats.literal);
    tables = {
      litContext,
      litClassCount,
      literal: buildContextLengths(mergeByClass(literalFull, litContext, litClassCount, 256), 256),
      token: buildContextLengths(stats.token, TOKEN_ALPHABET_SIZE),
      offset: buildContextLengths(stats.offset, OFFSET_SLOT_COUNT),
    };
  }
  return { top64, tables };
}

function collectStatistics(docs: string[], dictionary: Uint8Array, language: RegisteredLanguage): StreamStatistics {
  const stats: StreamStatistics = {
    literal: [new Float64Array(256 * 256), new Float64Array(256 * 256)],
    token: new Float64Array(TOKEN_CONTEXT_COUNT * TOKEN_ALPHABET_SIZE),
    offset: new Float64Array(OFFSET_CONTEXT_COUNT * OFFSET_SLOT_COUNT),
  };
  let statsBytes = 0;
  for (const [docIndex, doc] of docs.entries()) {
    if (statsBytes >= MAX_STATS_BYTES) break;
    const bytes = textEncoder.encode(doc);
    statsBytes += bytes.length;
    const literalFold = stats.literal[docIndex % 2]!;
    const tokens = parse(bytes, dictionary, dictIndexFor(language), smallPricing(bytes, language));
    let prevKind = TOKEN_KIND_LITRUN;
    const pushToken = (kind: number, lenValue: number): void => {
      stats.token[prevKind * TOKEN_ALPHABET_SIZE + kind * LENGTH_SLOT_COUNT + slotOf(lenValue)]!++;
      prevKind = kind;
    };
    for (const token of tokens) {
      if (token.type === 'lit') {
        pushToken(TOKEN_KIND_LITRUN, Math.min(token.end - token.start - 1, 262_143));
        for (let i = token.start; i < token.end; i++) {
          literalFold[(i > 0 ? bytes[i - 1]! : 0) * 256 + bytes[i]!]!++;
        }
      } else if (token.type === 'history') {
        if (token.rep >= 0) pushToken(TOKEN_KIND_REP0 + token.rep, token.len - MIN_LEN_REP);
        else {
          pushToken(TOKEN_KIND_HISTORY, token.len - MIN_LEN_REP);
          stats.offset[OFFSET_CONTEXT_HISTORY * OFFSET_SLOT_COUNT + slotOf(token.dist - 1)]!++;
        }
      } else {
        pushToken(TOKEN_KIND_DICT, token.len - MIN_LEN_REP);
        stats.offset[OFFSET_CONTEXT_DICT * OFFSET_SLOT_COUNT + slotOf(token.start)]!++;
      }
    }
  }
  return stats;
}

/** Sums per-context literal frequencies down to plain byte frequencies (for the top-64 charset). */
function marginalLiteralFreqs(literalFull: Float64Array): Float64Array {
  const freqs = new Float64Array(256);
  for (let ctx = 0; ctx < 256; ctx++) {
    for (let byte = 0; byte < 256; byte++) freqs[byte]! += literalFull[ctx * 256 + byte]!;
  }
  return freqs;
}

/** Sums joint `[ctx][symbol]` frequencies into `[classOf(ctx)][symbol]` frequencies. */
function mergeByClass(
  joint: Float64Array,
  classOf: Uint8Array,
  classCount: number,
  alphabetSize: number
): Float64Array {
  const merged = new Float64Array(classCount * alphabetSize);
  const contextCount = joint.length / alphabetSize;
  for (let ctx = 0; ctx < contextCount; ctx++) {
    const target = classOf[ctx]! * alphabetSize;
    for (let symbol = 0; symbol < alphabetSize; symbol++) {
      merged[target + symbol]! += joint[ctx * alphabetSize + symbol]!;
    }
  }
  return merged;
}

/** Builds smoothed package-merge code lengths independently for each context slice. */
function buildContextLengths(freqs: Float64Array, alphabetSize: number): Uint8Array {
  const lengths = new Uint8Array(freqs.length);
  for (let base = 0; base < freqs.length; base += alphabetSize) {
    lengths.set(buildLengths(smoothed(freqs.subarray(base, base + alphabetSize))), base);
  }
  return lengths;
}

/** Total bits (frequency-weighted self-information) of one conditional distribution. */
function entropyBits(freq: Float64Array): number {
  let sum = 0;
  for (const x of freq) sum += x;
  if (sum === 0) return 0;
  let bits = 0;
  for (const x of freq) if (x > 0) bits -= x * Math.log2(x / sum);
  return bits;
}

/** Cluster of merged literal contexts (see {@link chooseLiteralClasses}). */
interface Cluster {
  freq: Float64Array;
  members: number[];
  entropyBits: number;
}

/**
 * Greedy agglomerative context merging: contexts (previous-byte values) whose conditional
 * literal distributions are closest (smallest joint-entropy increase) merge first. Candidate
 * class counts are scored by two-fold cross-validation (fold-0-trained code lengths applied
 * to fold-1 frequencies and vice versa), so extra classes must pay for their own overfit.
 */
function chooseLiteralClasses(folds: [Float64Array, Float64Array]): {
  litContext: Uint8Array;
  litClassCount: number;
} {
  const full = new Float64Array(256 * 256);
  for (let i = 0; i < full.length; i++) full[i] = folds[0][i]! + folds[1][i]!;
  let total = 0;
  for (const x of full) total += x;

  // Active clusters: frequent contexts start alone; rare ones share one bucket.
  const clusters: Cluster[] = [];
  const rare: number[] = [];
  for (let ctx = 0; ctx < 256; ctx++) {
    const freq = full.subarray(ctx * 256, ctx * 256 + 256);
    let count = 0;
    for (const x of freq) count += x;
    if (count >= total * 0.0005) {
      clusters.push({ freq: Float64Array.from(freq), members: [ctx], entropyBits: entropyBits(freq) });
    } else rare.push(ctx);
  }
  if (rare.length > 0 || clusters.length === 0) {
    const freq = new Float64Array(256);
    for (const ctx of rare) {
      for (let byte = 0; byte < 256; byte++) freq[byte]! += full[ctx * 256 + byte]!;
    }
    clusters.push({ freq, members: rare, entropyBits: entropyBits(freq) });
  }

  // Merge down to LIT_CLASS_MAX, snapshotting each candidate class count on the way.
  const candidates = new Map<number, Uint8Array>();
  const snapshot = (): Uint8Array => {
    const classOf = new Uint8Array(256);
    for (const [cls, cluster] of clusters.entries()) for (const ctx of cluster.members) classOf[ctx] = cls;
    return classOf;
  };
  const candidateCounts = new Set([LIT_CLASS_MAX, 32, 16, 8, 4, 1]);
  const merged = new Float64Array(256);
  while (clusters.length > 1) {
    if (candidateCounts.has(clusters.length)) candidates.set(clusters.length, snapshot());
    let bestI = 0;
    let bestJ = 1;
    let bestDelta = Number.POSITIVE_INFINITY;
    for (let i = 0; i < clusters.length; i++) {
      for (let j = i + 1; j < clusters.length; j++) {
        for (let byte = 0; byte < 256; byte++) merged[byte] = clusters[i]!.freq[byte]! + clusters[j]!.freq[byte]!;
        const delta = entropyBits(merged) - clusters[i]!.entropyBits - clusters[j]!.entropyBits;
        if (delta < bestDelta) {
          bestDelta = delta;
          bestI = i;
          bestJ = j;
        }
      }
    }
    const a = clusters[bestI]!;
    const b = clusters[bestJ]!;
    for (let byte = 0; byte < 256; byte++) a.freq[byte]! += b.freq[byte]!;
    a.members.push(...b.members);
    a.entropyBits = entropyBits(a.freq);
    clusters.splice(bestJ, 1);
  }
  candidates.set(1, snapshot());

  // Cross-validated cost of each candidate: code lengths from one fold, symbol counts from the other.
  let bestCount = 1;
  let bestBits = Number.POSITIVE_INFINITY;
  for (const [count, classOf] of candidates) {
    let bits = 0;
    for (const [foldIndex, trainFold] of folds.entries()) {
      const evalFold = folds[1 - foldIndex]!;
      const lengths = buildContextLengths(mergeByClass(trainFold, classOf, count, 256), 256);
      for (let ctx = 0; ctx < 256; ctx++) {
        const base = classOf[ctx]! * 256;
        for (let byte = 0; byte < 256; byte++) {
          bits += evalFold[ctx * 256 + byte]! * lengths[base + byte]!;
        }
      }
    }
    if (bits < bestBits) {
      bestBits = bits;
      bestCount = count;
    }
  }
  return { litContext: candidates.get(bestCount)!, litClassCount: bestCount };
}

function makeLanguage(dictionary: Uint8Array, top64: Uint8Array, tables: EntropyTables): RegisteredLanguage {
  const top64Index = new Int8Array(256).fill(-1);
  for (let i = 0; i < 64; i++) if (top64Index[top64[i]!] === -1) top64Index[top64[i]!] = i;
  return { id: -1, name: 'training', dictionary, top64, top64Index, tables, dictIndex: undefined };
}

function byteFrequencies(docs: string[]): Float64Array {
  const freqs = new Float64Array(256);
  for (const doc of docs) for (const byte of textEncoder.encode(doc)) freqs[byte]!++;
  return freqs;
}

function rankTop64(freqs: Float64Array): Uint8Array {
  const order = [...freqs.keys()].toSorted((a, b) => freqs[b]! - freqs[a]! || a - b);
  return new Uint8Array(order.slice(0, 64));
}

/** +1 smoothing: every symbol keeps a code, so encoders never lose the Huffman path. */
function smoothed(freqs: Float64Array): Float64Array {
  return freqs.map((f) => f + 1);
}

function flatTables(): EntropyTables {
  return {
    litContext: new Uint8Array(256),
    litClassCount: 1,
    literal: buildLengths(new Float64Array(256).fill(1)),
    token: buildContextLengths(
      new Float64Array(TOKEN_CONTEXT_COUNT * TOKEN_ALPHABET_SIZE).fill(1),
      TOKEN_ALPHABET_SIZE
    ),
    offset: buildContextLengths(new Float64Array(OFFSET_CONTEXT_COUNT * OFFSET_SLOT_COUNT).fill(1), OFFSET_SLOT_COUNT),
  };
}

function moduleDataFields(top64: Uint8Array, tables: EntropyTables): string {
  return `  top64: fromBase64('${toBase64(top64)}'),
  tables: {
    litContext: fromBase64('${toBase64(tables.litContext)}'),
    litClassCount: ${tables.litClassCount},
    literal: fromBase64('${toBase64(tables.literal)}'),
    token: fromBase64('${toBase64(tables.token)}'),
    offset: fromBase64('${toBase64(tables.offset)}'),
  },
`;
}

function identifierFor(name: string): string {
  // 'en-US' → 'enUs' (strict camelCase, matching the repo's filename convention).
  return name.replaceAll(/-(\w+)/g, (_, part: string) => part[0]!.toUpperCase() + part.slice(1).toLowerCase());
}

function hasCorpus(name: string): boolean {
  return existsSync(join(CORPUS_DIR, name));
}

/**
 * Train-split docs only, allow-listed from the manifest: a sample trains only when it is
 * explicitly marked `split: "train"` and trainable. Stray files without manifest rows (or a
 * corpus that has not been through split.ts yet) contribute nothing — failing toward an empty
 * train set is safer than silently training on unlabeled or license-restricted data.
 */
function loadTrainDocs(name: string): string[] {
  // Training reads only the public corpus, never corpusDirs(): generated dictionaries embed
  // literal fragments of their training documents and are committed to this public
  // repository, so the auto-detected private corpus must stay benchmark-only.
  const dir = join(CORPUS_DIR, name);
  const manifestPath = join(dir, 'manifest.jsonl');
  if (!existsSync(manifestPath)) return [];
  const docs: string[] = [];
  for (const line of readFileSync(manifestPath, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const entry = JSON.parse(line) as { file: string; split?: string; trainable?: boolean };
    if (entry.split !== 'train' || entry.trainable === false) continue;
    const path = join(dir, entry.file);
    if (existsSync(path)) docs.push(readFileSync(path, 'utf8'));
  }
  return docs;
}

const GENERATED_HEADER = `// Generated by scripts/train/train.ts — do not edit by hand.
// oxlint-disable -- generated file
`;

const FALLBACK_SAMPLE = `# tokzip generic sample
This built-in sample trains the id-0 tables when no plain-text corpus has been fetched.
It mixes short English prose with typical code and JSON payloads, because the id-0 path
must degrade gracefully on anything: chat messages, markdown documents, configuration
files, and source snippets. The quick brown fox jumps over the lazy dog. She sells sea
shells by the sea shore, and the shells she sells are surely seashells.

\`\`\`typescript
export function greet(name: string): string {
  return \`Hello, \${name}!\`;
}
for (let i = 0; i < 10; i++) console.log(greet(String(i)));
\`\`\`

{"name":"example","version":"1.0.0","dependencies":{"left-pad":"^1.3.0"},"private":true}

However, the training corpus should be fetched with scripts/corpus/fetchOss.ts for real
use; these few paragraphs only make the bootstrap tables sane rather than representative.
`;

main();
