/**
 * Handcrafted shared wrapper dictionary content: scaffolding common to all languages —
 * markdown structure, JSON punctuation, generic prose connectives, and cross-language code
 * idioms. Trained language suffixes carry everything language-specific; this stays small
 * because it ships in core. Ordering puts the most valuable idioms at low offsets (cheapest
 * to reference in both wire formats).
 */
export const WRAPPER_IDIOMS: string[] = [
  // Markdown / documentation scaffolding (fences first: they dominate LLM output).
  '```typescript\n',
  '```javascript\n',
  '```python\n',
  '```json\n{\n  "',
  '```bash\n',
  '```\n\n',
  '\n```\n',
  '\n\n## ',
  '\n\n### ',
  '\n\n- ',
  '\n- ',
  '\n1. ',
  '**Note:** ',
  '**Example:**\n',
  '# ',
  '> ',
  '](https://',
  '](http://',
  '[](',
  '![',
  '---\n',
  '| --- | --- |\n',
  '| ',
  ' |\n',
  // JSON / config scaffolding.
  '{\n  "',
  '",\n  "',
  '": "',
  '": {',
  '": [',
  '"},{"',
  '":true,',
  '":false,',
  '":null,',
  '"name": "',
  '"version": "',
  '"description": "',
  '"type": "',
  '"value": ',
  '"id": ',
  'null}',
  'true,\n',
  'false,\n',
  // Cross-language code idioms.
  'function ',
  'return ',
  'const ',
  'import ',
  'export ',
  'public ',
  'private ',
  'static ',
  'class ',
  'string',
  'number',
  'boolean',
  'void ',
  'default',
  'if (',
  ') {\n',
  '} else {\n',
  '}\n}\n',
  ');\n',
  ' = ',
  ' == ',
  ' === ',
  ' != ',
  ' && ',
  ' || ',
  ' => {',
  'for (',
  'while (',
  'switch (',
  'case ',
  'break;\n',
  'continue;\n',
  'true',
  'false',
  'null',
  'undefined',
  'this.',
  'new ',
  'try {\n',
  '} catch (',
  'throw new ',
  'Error(',
  'console.log(',
  'print(',
  'printf(',
  'async ',
  'await ',
  'Promise',
  '() => ',
  '();\n',
  '.length',
  '.push(',
  '.map(',
  '.filter(',
  '.forEach(',
  'i++) {\n',
  '\n    ',
  '\n  ',
  '\n\t',
  ' */\n',
  '/* ',
  '// ',
  '/**\n * ',
  '\n * ',
  '#include <',
  'TODO: ',
  // Generic prose connectives (English dominates docs and commit messages).
  ' the ',
  ' and ',
  ' that ',
  ' with ',
  ' for ',
  ' this ',
  ' from ',
  ' are ',
  ' is ',
  ' to ',
  ' of ',
  ' in ',
  ' can be ',
  ' will be ',
  ' should ',
  ' because ',
  ' however, ',
  ' for example, ',
  ' such as ',
  ' as well as ',
  ' in order to ',
  ' based on ',
  ' depending on ',
  ' according to ',
  ' the following ',
  ' as follows:\n',
  '. In addition, ',
  '. Note that ',
  '. However, ',
  '. This ',
  ', which ',
  ', and ',
  ', or ',
  ', but ',
  'ing ',
  'tion ',
  'ment ',
  'able ',
  'value',
  'data',
  'file',
  'user',
  'name',
  'time',
  'test',
  'result',
  'error',
  'message',
  'request',
  'response',
  'object',
  'array',
  'index',
  'count',
  'items',
  'options',
  'config',
  'version',
  'example',
  'implementation',
  'application',
  'information',
  'documentation',
  'environment',
  'parameter',
  'argument',
  'property',
  'attribute',
  'element',
  'component',
  'interface',
  'module',
  'package',
  'library',
  'framework',
  'database',
  'server',
  'client',
  'update',
  'delete',
  'create',
  'remove',
  'return',
  'string',
  'output',
  'input',
];

export function buildWrapperDictionary(): Uint8Array {
  return new TextEncoder().encode(WRAPPER_IDIOMS.join(''));
}
