// Generated by scripts/train/train.ts — do not edit by hand.
// Barrel importing every trained language module (each self-registers on import).
import './c.ts';
import './cpp.ts';
import './csharp.ts';
import './css.ts';
import './dart.ts';
import './enUs.ts';
import './haskell.ts';
import './html.ts';
import './jaJp.ts';
import './java.ts';
import './javascript.ts';
import './jsp.ts';
import './php.ts';
import './python.ts';
import './ruby.ts';
import './rust.ts';
import './text.ts';
import './typescript.ts';
import './zhCn.ts';
import './zhTw.ts';
import './zig.ts';
